"""empty message

Revision ID: 6a8b1ec86bb4
Revises: 780d07190926
Create Date: 2018-01-15 10:32:16.445216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a8b1ec86bb4'
down_revision = '780d07190926'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.String(), nullable=True))
    op.drop_column('users', 'nome')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('nome', sa.VARCHAR(), nullable=True))
    op.drop_column('users', 'name')
    # ### end Alembic commands ###
