"""empty message

Revision ID: cb644262ded1
Revises: 
Create Date: 2018-12-14 07:43:50.526967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb644262ded1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assinante',
    sa.Column('codpessoa', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('telefonefixo', sa.String(length=15), nullable=True),
    sa.Column('telefonecel', sa.String(length=15), nullable=True),
    sa.Column('email', sa.String(length=60), nullable=False),
    sa.Column('senha', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('codpessoa'),
    sa.UniqueConstraint('email')
    )
    op.create_table('casaespetaculos',
    sa.Column('codcasa', sa.Integer(), nullable=False),
    sa.Column('nomecasa', sa.String(length=30), nullable=False),
    sa.Column('telefone', sa.String(length=15), nullable=True),
    sa.Column('piso', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('site', sa.String(length=70), nullable=True),
    sa.PrimaryKeyConstraint('codcasa')
    )
    op.create_table('loja',
    sa.Column('codloja', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nomeloja', sa.String(length=30), nullable=False),
    sa.Column('piso', sa.Integer(), nullable=False),
    sa.Column('numloja', sa.Integer(), nullable=False),
    sa.Column('telefone', sa.String(length=15), nullable=True),
    sa.Column('site', sa.String(length=70), nullable=True),
    sa.PrimaryKeyConstraint('codloja')
    )
    op.create_table('newsletter',
    sa.Column('codnewsletter', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('conteudo', sa.Text(), nullable=False),
    sa.Column('categoria', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('codnewsletter')
    )
    op.create_table('produto',
    sa.Column('cod_produto', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('cod_produto')
    )
    op.create_table('shopping',
    sa.Column('nome', sa.String(length=70), nullable=False),
    sa.Column('endereco', sa.String(length=70), nullable=False),
    sa.Column('horarioFuncionamento', sa.String(length=40), nullable=True),
    sa.Column('telefone', sa.String(length=15), nullable=False),
    sa.PrimaryKeyConstraint('nome')
    )
    op.create_table('usuario',
    sa.Column('codpessoa', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('telefonefixo', sa.String(length=15), nullable=True),
    sa.Column('telefonecel', sa.String(length=15), nullable=True),
    sa.Column('email', sa.String(length=60), nullable=False),
    sa.Column('senha', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('codpessoa'),
    sa.UniqueConstraint('email')
    )
    op.create_table('categoria_loja',
    sa.Column('loja', sa.Integer(), nullable=False),
    sa.Column('categoriaLoja', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['loja'], ['loja.codloja'], ),
    sa.PrimaryKeyConstraint('loja', 'categoriaLoja')
    )
    op.create_table('categoria_produto',
    sa.Column('produto', sa.Integer(), nullable=False),
    sa.Column('categoria_produto', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['produto'], ['produto.cod_produto'], ),
    sa.PrimaryKeyConstraint('produto', 'categoria_produto')
    )
    op.create_table('contem',
    sa.Column('loja', sa.Integer(), nullable=False),
    sa.Column('produto', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['loja'], ['loja.codloja'], ),
    sa.ForeignKeyConstraint(['produto'], ['produto.cod_produto'], ),
    sa.PrimaryKeyConstraint('loja', 'produto')
    )
    op.create_table('envia_para',
    sa.Column('assinante', sa.Integer(), nullable=False),
    sa.Column('newsletter', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['assinante'], ['assinante.codpessoa'], ),
    sa.ForeignKeyConstraint(['newsletter'], ['newsletter.codnewsletter'], ),
    sa.PrimaryKeyConstraint('assinante', 'newsletter')
    )
    op.create_table('estacionamento',
    sa.Column('nome', sa.String(length=70), nullable=False),
    sa.Column('shopping', sa.String(length=70), nullable=True),
    sa.Column('telefone', sa.String(length=15), nullable=False),
    sa.Column('numvagas', sa.Integer(), nullable=False),
    sa.Column('horariofuncionamento', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['shopping'], ['shopping.nome'], ),
    sa.PrimaryKeyConstraint('nome')
    )
    op.create_table('funcionario_casa_espetaculos',
    sa.Column('codpessoa', sa.Integer(), nullable=False),
    sa.Column('codfuncionario', sa.Integer(), nullable=True),
    sa.Column('casaespetaculos', sa.Integer(), nullable=True),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('telefonefixo', sa.String(length=15), nullable=True),
    sa.Column('telefonecel', sa.String(length=15), nullable=True),
    sa.Column('email', sa.String(length=60), nullable=False),
    sa.Column('senha', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['casaespetaculos'], ['casaespetaculos.codcasa'], ),
    sa.PrimaryKeyConstraint('codpessoa'),
    sa.UniqueConstraint('email')
    )
    op.create_table('funcionario_loja',
    sa.Column('codpessoa', sa.Integer(), nullable=False),
    sa.Column('codfuncionario', sa.Integer(), nullable=False),
    sa.Column('loja', sa.Integer(), nullable=True),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('telefonefixo', sa.String(length=15), nullable=True),
    sa.Column('telefonecel', sa.String(length=15), nullable=True),
    sa.Column('email', sa.String(length=60), nullable=False),
    sa.Column('senha', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['loja'], ['loja.codloja'], ),
    sa.PrimaryKeyConstraint('codpessoa'),
    sa.UniqueConstraint('email')
    )
    op.create_table('hotel',
    sa.Column('nome', sa.String(length=70), nullable=False),
    sa.Column('shopping', sa.String(length=70), nullable=True),
    sa.Column('site', sa.String(length=70), nullable=False),
    sa.Column('endereco', sa.String(length=70), nullable=False),
    sa.ForeignKeyConstraint(['shopping'], ['shopping.nome'], ),
    sa.PrimaryKeyConstraint('nome')
    )
    op.create_table('sala',
    sa.Column('codsala', sa.Integer(), nullable=False),
    sa.Column('numsala', sa.Integer(), nullable=False),
    sa.Column('numcadeiras', sa.Integer(), nullable=False),
    sa.Column('_3D', sa.Boolean(), nullable=True),
    sa.Column('casaespetaculos', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['casaespetaculos'], ['casaespetaculos.codcasa'], ),
    sa.PrimaryKeyConstraint('codsala')
    )
    op.create_table('servicos',
    sa.Column('codservico', sa.Integer(), nullable=False),
    sa.Column('shopping', sa.String(length=70), nullable=True),
    sa.Column('nome', sa.String(length=70), nullable=False),
    sa.Column('horariofuncionamento', sa.String(length=40), nullable=False),
    sa.Column('descricao', sa.String(length=300), nullable=False),
    sa.Column('localizacao', sa.String(length=70), nullable=False),
    sa.ForeignKeyConstraint(['shopping'], ['shopping.nome'], ),
    sa.PrimaryKeyConstraint('codservico')
    )
    op.create_table('espetaculo',
    sa.Column('cod_espetaculo', sa.Integer(), nullable=False),
    sa.Column('codsala', sa.Integer(), nullable=True),
    sa.Column('nome', sa.String(length=70), nullable=False),
    sa.Column('duracao', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=300), nullable=False),
    sa.Column('classificacao', sa.Integer(), nullable=False),
    sa.Column('linguagem', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['codsala'], ['sala.codsala'], ),
    sa.PrimaryKeyConstraint('cod_espetaculo')
    )
    op.create_table('categoria_espetaculo',
    sa.Column('espetaculo', sa.Integer(), nullable=False),
    sa.Column('categoria_espetaculo', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['espetaculo'], ['espetaculo.cod_espetaculo'], ),
    sa.PrimaryKeyConstraint('espetaculo', 'categoria_espetaculo')
    )
    op.create_table('sessao',
    sa.Column('cod_sessao', sa.Integer(), nullable=False),
    sa.Column('espetaculo', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('hora', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['espetaculo'], ['espetaculo.cod_espetaculo'], ),
    sa.PrimaryKeyConstraint('cod_sessao', 'espetaculo')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sessao')
    op.drop_table('categoria_espetaculo')
    op.drop_table('espetaculo')
    op.drop_table('servicos')
    op.drop_table('sala')
    op.drop_table('hotel')
    op.drop_table('funcionario_loja')
    op.drop_table('funcionario_casa_espetaculos')
    op.drop_table('estacionamento')
    op.drop_table('envia_para')
    op.drop_table('contem')
    op.drop_table('categoria_produto')
    op.drop_table('categoria_loja')
    op.drop_table('usuario')
    op.drop_table('shopping')
    op.drop_table('produto')
    op.drop_table('newsletter')
    op.drop_table('loja')
    op.drop_table('casaespetaculos')
    op.drop_table('assinante')
    # ### end Alembic commands ###
